#!/bin/bash

## Files and CMD
FILE="$HOME/.cache/eww_launch.system"
EWW=`which eww`

## Open widgets 
run_eww() {
	${EWW} open system
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww
else
	${EWW} close system
	rm "$FILE"
fi
